package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCertificate<M extends BaseCertificate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setNo(java.lang.String no) {
		set("NO", no);
	}

	public java.lang.String getNo() {
		return get("NO");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setContent(java.lang.String content) {
		set("CONTENT", content);
	}

	public java.lang.String getContent() {
		return get("CONTENT");
	}

	public void setStartTime(java.util.Date startTime) {
		set("START_TIME", startTime);
	}

	public java.util.Date getStartTime() {
		return get("START_TIME");
	}

	public void setEndTime(java.util.Date endTime) {
		set("END_TIME", endTime);
	}

	public java.util.Date getEndTime() {
		return get("END_TIME");
	}

	public void setUnit(java.lang.String unit) {
		set("UNIT", unit);
	}

	public java.lang.String getUnit() {
		return get("UNIT");
	}

}
