package com.sinorail.gysglbj.model;

import com.sinorail.gysglbj.model.base.BaseCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Certificate extends BaseCertificate<Certificate> {
	public static final Certificate dao = new Certificate().dao();
}
