package com.sinorail.gysglbj.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.gysglbj.model.base.BaseCertificateSupcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CertificateSupcode extends BaseCertificateSupcode<CertificateSupcode> {
	public static final CertificateSupcode dao = new CertificateSupcode().dao();

	public Object queryById(String cerId) {
		/*List<Record> find = Db.find(getSql("certificatesupcode.selectById"),cerId); 
		System.out.println(find);*/
		/*CertificateSupcode findFirst = findFirst(getSql("certificatesupcode.selectById"),cerId);*/
		return findFirst(getSql("certificatesupcode.selectById"),cerId);
	}
}
