package com.sinorail.gysglbj.model;

import com.sinorail.gysglbj.model.base.BaseQuote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Quote extends BaseQuote<Quote> {
	public static final Quote dao = new Quote().dao();
}
